services:

  metalp:
    image: php:8.3.9-apache
    volumes:
      - metalp-webshare:/var/www/html:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metalp.tls=true"
      - "traefik.http.routers.metalp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.metalp.rule=Host(`metalp.epfl.ch`)"

volumes:
  metalp-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: addr=enac1arch.epfl.ch,username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},ro
      device: "//enac1arch.epfl.ch/ENAC-IT/webhosting/metalp/metalp/"
